export const TRACKCAM_CONFIG_KEYS = [
  'intervaloPosicionSegundos',
  'intervaloPosicionDetenidoSegundos',
  'velocidadMinimaAlarmasKmh',
  'canal1Activo',
  'canal2Activo',
  'canal3Activo',
  'canal4Activo',
  'canal5Activo',
  'alarmaFatiga',
  'umbralFatiga',
  'alarmaTelefono',
  'alarmaFumar',
  'alarmaDistraccion',
  'alarmaConductorAusente',
  'alarmaCinturon',
  'alarmaObstruccionCamara',
  'alarmaColisionFrontal',
  'alarmaSalidaCarril',
  'alarmaDistanciaCorta',
  'distanciaCortaSegundos',
  'alarmaColisionPeaton',
  'alarmaCambioCarrilFrecuente',
  'alarmaExcesoSenalTransito',
  'alarmaObstaculo',
  'alarmaFallaAdas',
  'alarmaAceleracionBrusca',
  'umbralAceleracionG',
  'alarmaFrenadoBrusco',
  'umbralFrenadoG',
  'alarmaGiroBrusco',
  'umbralGiroG',
  'alarmaRalenti',
  'alarmaApagadoAnormal',
  'alarmaAproximacionTrasera',
  'alarmaAproximacionTraseraIzq',
  'alarmaAproximacionTraseraDer',
  'alarmaExcesoVelocidad',
  'velocidadMaximaKmh',
  'alarmaFatigaTiempo',
  'alarmaColision',
  'colisionAceleracionG',
  'alarmaVolteo',
] as const;

export type TrackcamConfigKey = (typeof TRACKCAM_CONFIG_KEYS)[number];
